[package]
name = "proxy-rs"
version = "0.3.5"
edition = "2021"
readme = "README.md"
description = "Fast Rust-based proxy checker"
repository = "https://github.com/zevtyardt/proxy.rs"
license = "MIT"
keywords = ["proxy", "scraper", "checker", "server"]
categories = ["command-line-utilities"]
exclude = ["/data"]
authors = ["zevtyardt"]

[dependencies]
async-recursion = "1.0.4"
async_once = "0.2.6"
autocompress = { version = "0.2.2", features = ["full"] }
byteorder = "1.4.3"
byteorder-pack = "0.1.0"
clap = { version = "4.3.1", features = ["derive"] }
concurrent-queue = "2.2.0"
dashmap = "5.5.0"
directories = "5.0.1"
futures-util = "0.3.28"
httparse = "1.8.0"
hyper = { version = "0.14.27", features = ["full"] }
hyper-tls = "0.5.0"
indicatif = { version = "0.17.3", features = ["rayon"] }
lazy_static = "1.4.0"
log = "0.4.17"
maxminddb = "0.23.0"
md5 = "0.7.0"
native-tls = "0.2.11"
parking_lot = "0.12.1"
rand = "0.8.5"
regex = "1.8.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
simple_logger = { version = "4.1.0", features = ["stderr"] }
tokio = { version = "1.28.0", features = ["rt-multi-thread", "net", "time", "io-std", "fs"] }
tokio-native-tls = "0.3.1"
trust-dns-resolver = "0.22.0"
url = "2.3.1"
